data.lifeMul = 160
data.team1VS2Life = 180
data.turnsRecoveryRate = 100
data.teamLifeShare = false
data.zoomActive = true
data.zoomMin = 0.75
data.zoomMax = 1.1
data.zoomSpeed = 1
data.roundTime = 321
data.numTurns = 4
data.numSimul = 4
data.simulType = 'Tag'
data.disablePadP1 = false
data.disablePadP2 = false
data.difficulty = 5
data.continueCount = 0
data.contSelection = false
data.aiRamping = true
data.autoguard = false
data.vsDisplayWin = true
data.lifebar = 'data/screenpack/fightSD.def'
data.sffConversion = true
data.language = 'ENGLISH'
data.menuSong = 'Random'
data.clock = 'Standard'
data.date = 'Type A'
data.selectType = 'Fixed'
data.stageType = 'Modern'
data.winscreen = 'Classic'
data.debugMode = false
data.usxChar = false
data.challengerSong = 'Fixed'
data.charPresentation = 'Mixed'
data.training = 'Fixed'
data.coopenemy = 'Simul'
data.userName = 'USX PLAYER'
data.usx = 'Unlimited Edition'
